# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               API-Design
tagline:             'Praxishandbuch für Java- und Webservice-Entwickler'
#url:                 http://api-design.de
baseurl:             http://api-design.de
baseurl:             ''
paginate:            5
gems:                [jekyll-paginate]
paginate_path:       "blog/page:num"
