# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               API-Design
tagline:             'Praxishandbuch für Java- und Webservice-Entwickler'
url:                 http://kspichale.github.io/api-design-website
baseurl:             http://kspichale.github.io/api-design-website
#baseurl:             ''
paginate:            5
gems:                [jekyll-paginate]
paginate_path:       "blog/page:num"
